spring:
  application:
    name: dou-ai-agent
  profiles:
    active: local
# 这里的local实际引用的 application-local.yml中配置的参数
  ai:
    vectorstore:
      pgvector:
      index-type: HNSW
      distance-type: COSINE_DISTANCE
      dimensions: 1536
      max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
    mcp: #mcp服务的配置
      client:
#        sse:
 #         connections:
  #          server1:
   #           url: http://localhost:8127
        stdio: #因为是本地调用的，所以配置stdio模式
          servers-configuration: classpath:mcp-servers.json


server:
  port: 8123
  servlet:
    context-path: /api

# springdoc-openapi  生成接口文档
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.dou.douaiagent.controller
# knife4j 生成接口文档
knife4j:
  enable: true
  setting:
    language: zh_cn

# mybatis-plus 框架中 实体字段与库表字段一致，不需要框架默认拆分字段如username 拆成user_name
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false